/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminLayoutRouteImport } from './routes/admin/_layout'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as BooksIndexRouteImport } from './routes/books/index'
import { Route as BooksBookIdRouteImport } from './routes/books/$bookId'
import { Route as OrderIndexRouteImport } from './routes/order/index'
import { Route as AdminLayoutIndexRouteImport } from './routes/admin/_layout/index'
import { Route as AdminLayoutOrdersRouteImport } from './routes/admin/_layout/orders'
import { Route as AdminLayoutStylesRouteImport } from './routes/admin/_layout/styles'
import { Route as AdminLayoutBooksIndexRouteImport } from './routes/admin/_layout/books/index'
import { Route as AdminLayoutBooksBookIdRouteImport } from './routes/admin/_layout/books/$bookId'
import { Route as AdminLayoutBooksNewRouteImport } from './routes/admin/_layout/books/new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLayoutRoute = AdminLayoutRouteImport.update({
  id: '/admin/_layout',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const BooksIndexRoute = BooksIndexRouteImport.update({
  id: '/books/',
  path: '/books/',
  getParentRoute: () => rootRouteImport,
} as any)
const BooksBookIdRoute = BooksBookIdRouteImport.update({
  id: '/books/$bookId',
  path: '/books/$bookId',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderIndexRoute = OrderIndexRouteImport.update({
  id: '/order/',
  path: '/order/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLayoutIndexRoute = AdminLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const AdminLayoutOrdersRoute = AdminLayoutOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const AdminLayoutStylesRoute = AdminLayoutStylesRouteImport.update({
  id: '/styles',
  path: '/styles',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const AdminLayoutBooksIndexRoute = AdminLayoutBooksIndexRouteImport.update({
  id: '/books/',
  path: '/books/',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const AdminLayoutBooksBookIdRoute = AdminLayoutBooksBookIdRouteImport.update({
  id: '/books/$bookId',
  path: '/books/$bookId',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const AdminLayoutBooksNewRoute = AdminLayoutBooksNewRouteImport.update({
  id: '/books/new',
  path: '/books/new',
  getParentRoute: () => AdminLayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminLayoutRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/books/$bookId': typeof BooksBookIdRoute
  '/books/': typeof BooksIndexRoute
  '/order/': typeof OrderIndexRoute
  '/admin/orders': typeof AdminLayoutOrdersRoute
  '/admin/styles': typeof AdminLayoutStylesRoute
  '/admin/': typeof AdminLayoutIndexRoute
  '/admin/books/$bookId': typeof AdminLayoutBooksBookIdRoute
  '/admin/books/new': typeof AdminLayoutBooksNewRoute
  '/admin/books/': typeof AdminLayoutBooksIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/login': typeof AdminLoginRoute
  '/books/$bookId': typeof BooksBookIdRoute
  '/books': typeof BooksIndexRoute
  '/order': typeof OrderIndexRoute
  '/admin/orders': typeof AdminLayoutOrdersRoute
  '/admin/styles': typeof AdminLayoutStylesRoute
  '/admin': typeof AdminLayoutIndexRoute
  '/admin/books/$bookId': typeof AdminLayoutBooksBookIdRoute
  '/admin/books/new': typeof AdminLayoutBooksNewRoute
  '/admin/books': typeof AdminLayoutBooksIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin/_layout': typeof AdminLayoutRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/books/$bookId': typeof BooksBookIdRoute
  '/books/': typeof BooksIndexRoute
  '/order/': typeof OrderIndexRoute
  '/admin/_layout/orders': typeof AdminLayoutOrdersRoute
  '/admin/_layout/styles': typeof AdminLayoutStylesRoute
  '/admin/_layout/': typeof AdminLayoutIndexRoute
  '/admin/_layout/books/$bookId': typeof AdminLayoutBooksBookIdRoute
  '/admin/_layout/books/new': typeof AdminLayoutBooksNewRoute
  '/admin/_layout/books/': typeof AdminLayoutBooksIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin/login'
    | '/books/$bookId'
    | '/books/'
    | '/order/'
    | '/admin/orders'
    | '/admin/styles'
    | '/admin/'
    | '/admin/books/$bookId'
    | '/admin/books/new'
    | '/admin/books/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/login'
    | '/books/$bookId'
    | '/books'
    | '/order'
    | '/admin/orders'
    | '/admin/styles'
    | '/admin'
    | '/admin/books/$bookId'
    | '/admin/books/new'
    | '/admin/books'
  id:
    | '__root__'
    | '/'
    | '/admin/_layout'
    | '/admin/login'
    | '/books/$bookId'
    | '/books/'
    | '/order/'
    | '/admin/_layout/orders'
    | '/admin/_layout/styles'
    | '/admin/_layout/'
    | '/admin/_layout/books/$bookId'
    | '/admin/_layout/books/new'
    | '/admin/_layout/books/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminLayoutRoute: typeof AdminLayoutRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
  BooksBookIdRoute: typeof BooksBookIdRoute
  BooksIndexRoute: typeof BooksIndexRoute
  OrderIndexRoute: typeof OrderIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_layout': {
      id: '/admin/_layout'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/books/': {
      id: '/books/'
      path: '/books'
      fullPath: '/books/'
      preLoaderRoute: typeof BooksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/books/$bookId': {
      id: '/books/$bookId'
      path: '/books/$bookId'
      fullPath: '/books/$bookId'
      preLoaderRoute: typeof BooksBookIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order/': {
      id: '/order/'
      path: '/order'
      fullPath: '/order/'
      preLoaderRoute: typeof OrderIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_layout/': {
      id: '/admin/_layout/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminLayoutIndexRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/orders': {
      id: '/admin/_layout/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminLayoutOrdersRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/styles': {
      id: '/admin/_layout/styles'
      path: '/styles'
      fullPath: '/admin/styles'
      preLoaderRoute: typeof AdminLayoutStylesRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/books/': {
      id: '/admin/_layout/books/'
      path: '/books'
      fullPath: '/admin/books/'
      preLoaderRoute: typeof AdminLayoutBooksIndexRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/books/$bookId': {
      id: '/admin/_layout/books/$bookId'
      path: '/books/$bookId'
      fullPath: '/admin/books/$bookId'
      preLoaderRoute: typeof AdminLayoutBooksBookIdRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/books/new': {
      id: '/admin/_layout/books/new'
      path: '/books/new'
      fullPath: '/admin/books/new'
      preLoaderRoute: typeof AdminLayoutBooksNewRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
  }
}

interface AdminLayoutRouteChildren {
  AdminLayoutOrdersRoute: typeof AdminLayoutOrdersRoute
  AdminLayoutStylesRoute: typeof AdminLayoutStylesRoute
  AdminLayoutIndexRoute: typeof AdminLayoutIndexRoute
  AdminLayoutBooksBookIdRoute: typeof AdminLayoutBooksBookIdRoute
  AdminLayoutBooksNewRoute: typeof AdminLayoutBooksNewRoute
  AdminLayoutBooksIndexRoute: typeof AdminLayoutBooksIndexRoute
}

const AdminLayoutRouteChildren: AdminLayoutRouteChildren = {
  AdminLayoutOrdersRoute: AdminLayoutOrdersRoute,
  AdminLayoutStylesRoute: AdminLayoutStylesRoute,
  AdminLayoutIndexRoute: AdminLayoutIndexRoute,
  AdminLayoutBooksBookIdRoute: AdminLayoutBooksBookIdRoute,
  AdminLayoutBooksNewRoute: AdminLayoutBooksNewRoute,
  AdminLayoutBooksIndexRoute: AdminLayoutBooksIndexRoute,
}

const AdminLayoutRouteWithChildren = AdminLayoutRoute._addFileChildren(
  AdminLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminLayoutRoute: AdminLayoutRouteWithChildren,
  AdminLoginRoute: AdminLoginRoute,
  BooksBookIdRoute: BooksBookIdRoute,
  BooksIndexRoute: BooksIndexRoute,
  OrderIndexRoute: OrderIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
